Desapeguei_project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #rota para o acesso de administração
    path('admin/', admin.site.urls),
    #rota para acessar as configurações de login
    path('accounts/', include('allauth.urls')),
    #rotas dos aplicativos
    path('',include('Home_app.urls')),
    path('perfil/',include('Perfil_app.urls')),
    #3rd party rotas
    path('ratings/', include('star_ratings.urls', namespace='ratings')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Home_app/urls.py
from django.urls import include, path

app_name = 'Home_app'

from . import views

urlpatterns = [
    path('',views.HomeTemplateView.as_view(),name='Home'),
    path('shop/',views.ShopTemplateView.as_view(),name='Shop'),
    path('detalhe-do-produto/<slug:id_produto>/',views.DetailTemplateView.as_view(),name='Detail'),
    path('contact/',views.ContactTemplteView.as_view(),name='Contact'),
    path('checkout/',views.CheckoutTemplateView.as_view(),name='Checkout'),
    path('cart/',views.CartTemplateView.as_view(),name='Cart'),
    path('vender-produto/',views.VenderProdutoView.as_view(),name='vender_produto'),
    path('perfil/publicacoes-historico/',views.HistoricoPublicacaoCompletoListView.as_view(),name='historico_publicacao'),
    path('perfil/historicos/',views.HistoricosListView.as_view(),name='historicos'),
    path('categoria-filtro/<categoria_id>',views.CategoriaFiltragemDetailView.as_view(),name='categoria_filtro'),
    path('populate',views.populate,),
    #LEMBRETE tirar a rota daqui e por no aplicativo Perfil_app.urls
    
    path('criar_comentario/',views.criar_comentario,name='criar_comentario')
    
]

Perfil_app/urls.py
from django.urls import path

from . import views

app_name = 'Perfil_app'

urlpatterns = [
    path('',views.PerfilTemplateView.as_view(),name='Perfil')
]

allauth/urls.py
from importlib import import_module

from django.urls import include, path

from allauth.socialaccount import providers

from . import app_settings


urlpatterns = [path("", include("allauth.account.urls"))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [path("social/", include("allauth.socialaccount.urls"))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + ".urls")
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, "urlpatterns", None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

star_ratings/urls.py
from __future__ import unicode_literals

from django.urls import re_path

from .views import Rate
from . import app_settings


urlpatterns = [
    re_path(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
]

app_name = 'star_ratings'

star_ratings/forms.py
from __future__ import absolute_import
from django import forms

from . import get_star_ratings_rating_model, app_settings
from .models import UserRating


class CreateUserRatingForm(forms.ModelForm):
    clear = forms.BooleanField(required=False)

    class Meta:
        model = UserRating
        exclude = [
            'count',
            'total',
            'average',
            'rating',
        ]

    def __init__(self, obj=None, *args, **kwargs):
        self.obj = obj
        super(CreateUserRatingForm, self).__init__(*args, **kwargs)

        if self.data.get('clear', False) and app_settings.STAR_RATINGS_CLEARABLE:
            self.fields['score'].required = False

    def save(self, commit=True):
        return get_star_ratings_rating_model().objects.rate(
            self.obj,
            self.cleaned_data['score'],
            user=self.cleaned_data['user'],
            ip=self.cleaned_data['ip'],
            clear=self.cleaned_data['clear'],
        )

Home_app/views.py
import decimal

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, ListView, TemplateView
from Comentarios_app.forms import ComentarioManualForm
from Comentarios_app.models import Comentario

from Historico_app.models import Historico
from Perfil_app.models import Perfil
from Produtos_app.forms import ProdutoManualForm
from Produtos_app.models import Categoria, Produto

TEMPLATE_HISTORICO_PUBLICACAO_PATH = 'Home_app/hitorico-publicacao.html'
TEMPLATE_HISTORICO_PATH = 'Home_app/historicos.html'
class HomeTemplateView(TemplateView):
    template_name = "Home_app/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categorias"] = Categoria.objects.all()
        context["produtos"] = Produto.objects.filter(disponivel=True).order_by('-data_de_publicacao')#lista de produtos masi recentes
        #talvez trocar o a chave para produtos_recentes
        context["produtos_mais_votados"] = Produto.objects.filter(disponivel=True).order_by('ratings')
        return context
    

class ShopTemplateView(ListView):
    model = Produto
    paginate_by = 9
    template_name = "Home_app/shop.html"
    context_object_name = 'produtos'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["produtos"] = Produto.objects.filter(disponivel=True)
        return context
    
    
    def post(self,request):
        context = dict()
        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            if self.request.POST.get('mais-recentes') is not None:
                context["produtos"] = Produto.objects.filter(disponivel=True).order_by('-data_de_publicacao')
            else:
                context['produtos'] = Produto.objects.filter(disponivel=True).order_by('-ratings')
        return render(self.request,"Home_app/shop.html",context=context)

class DetailTemplateView(DetailView):
    pk_url_kwarg = 'id_produto'
    template_name = "Home_app/detail.html"
    model = Produto
    context_object_name = 'produto'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["produtos_sugestao"] = Produto.objects.all().order_by('-ratings')[0:5]
        context["form"] = ComentarioManualForm
        context["comentarios"] = Comentario.objects.filter(produto=self.get_object())
        context["ja_comentou"] = Comentario.objects.filter(produto=self.get_object(), comentado_por=self.request.user.perfil).exists()
        return context

    def post(self,request,*args, **kwargs):
        quantidade_comprada_produto = int(self.request.POST.get("quantidade_a_ser_comprada"))
        #produto = self.get_object()#sera que essse metodo não é funcional ?
        produto = Produto.objects.get(pk=self.get_object().pk)
        comprador = self.request.user.perfil
        vendedor = Perfil.objects.get(pk=produto.publicado_por.pk)
        compra_total = decimal.Decimal(quantidade_comprada_produto) * produto.preco
        if produto.quantidade >= int(quantidade_comprada_produto):#se a quantidade for maior ou igual comprada
            Historico.objects.create(
            comprador=comprador,
            vendedor=produto.publicado_por,
            produto=produto,
            quantidade_comprada=int(quantidade_comprada_produto),
            preco=produto.preco,
            acao='Comprar',
            )
            produto.quantidade -= quantidade_comprada_produto
            if produto.quantidade == 0:
                produto.disponivel = False
            produto.save()
            vendedor.saldo += compra_total
            vendedor.save()
            comprador.saldo -= compra_total
            comprador.save()
        else:
            return HttpResponse("Tentativa de burlar o sistema detectatdo!, quantidade a ser comprada : {} , quantidade disponivel : {}".format(quantidade_comprada_produto, produto.quantidade))
        return redirect(reverse('Home_app:Detail',args=[self.get_object().id]))

    

class ProdutoCategoriaListView(ListView):
    model = Categoria
    template_name = ".html"


class ContactTemplteView(TemplateView):
    template_name = "Home_app/contact.html"

class CheckoutTemplateView(TemplateView):
    template_name = "Home_app/checkout.html"

class CartTemplateView(TemplateView):
    template_name = "Home_app/cart.html"

class VenderProdutoView(TemplateView):  
    template_name = "Home_app/vender-produto.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(f'{self.request.POST}')
        usuario = self.request.user
        context["formmanual"] = ProdutoManualForm
        context["usuario"] = usuario
        context["prateleira"] = Produto.objects.filter(publicado_por=usuario.perfil).order_by('-data_de_publicacao')[0:5]
        return context
    
    def post(self,*args, **kwargs):
        formulario = ProdutoManualForm(self.request.POST)
        if formulario.is_valid():
            foto = self.request.POST.get('foto')
            nome = self.request.POST.get('nome')
            preco = self.request.POST.get('preco')
            descricao = self.request.POST.get('descricao')
            quantidade = self.request.POST.get('quantidade')
            categoria = self.request.POST.get('categoria')
            Produto.objects.create(
                publicado_por=self.get_context_data().get('usuario').perfil,
                foto=foto,
                nome=nome,
                preco=preco,
                descricao=descricao,
                quantidade=quantidade,
                categoria=Categoria.objects.get(slug=categoria),
            )
            formulario = ProdutoManualForm()#limpar os campos
        return redirect(reverse('Home_app:vender_produto'))
        
class HistoricoPublicacaoCompletoListView(ListView):
    template_name = TEMPLATE_HISTORICO_PUBLICACAO_PATH
    paginate_by = 10
    model = Produto
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['historico_publicacao'] = Produto.objects.filter(publicado_por=self.request.user.perfil)#funcionando sem isso ?
        return context
    
    
class HistoricosListView(ListView):
    template_name = TEMPLATE_HISTORICO_PATH
    paginate_by = 10
    model = Historico
    context_object_name = 'historicos'


class CategoriaFiltragemDetailView(DetailView):
    model = Categoria
    template_name = "Home_app/shop.html"
    pk_url_kwarg = 'categoria_id'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["produtos"] = Produto.objects.filter(categoria=self.get_object())
        return context
    
def criar_comentario(request):
    print("{}".format(request.POST))
    comentario_novo = Comentario.objects.create(
        comentado_por=Perfil.objects.get(pk=request.user.perfil.pk),
        produto=Produto.objects.get(pk=request.POST.get("produto")),
        comentario=request.POST.get('comentario')
    ).save()
    return redirect(reverse('Home_app:Detail',args=(comentario_novo.produto.pk)))


def populate(request):
    categorias = ["Tecnologia","Remedios","Moveis","Eletrodomesticos","Construção"]
    for categoria in categorias:
        Categoria.objects.create(categoria=categoria,slug=categoria)
    return HttpResponseRedirect(reverse("Home_app:Home"))

star_ratings/views.py
from __future__ import unicode_literals

import copy

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, JsonResponse
from django.views.generic import View

from . import app_settings, get_star_ratings_rating_model
from .forms import CreateUserRatingForm
from .compat import is_authenticated
import json


class Rate(View):
    model = get_star_ratings_rating_model()

    def get_object(self):
        """
        Returns the model instance we're rating from the URL params.
        """
        content_type = ContentType.objects.get_for_id(self.kwargs.get('content_type_id'))
        return content_type.get_object_for_this_type(pk=self.kwargs.get('object_id'))

    def post(self, request, *args, **kwargs):
        def _post(request, *args, **kwargs):
            data = request.POST or json.loads(request.body.decode())

            data = copy.deepcopy(data)
            return_url = data.pop('next', '/')
            if type(return_url) == list:
                return_url = return_url[0]

            if 'HTTP_X_REAL_IP' in self.request.META:
                data['ip'] = self.request.META['HTTP_X_REAL_IP']
            else:
                data['ip'] = self.request.META['REMOTE_ADDR']

            data['user'] = is_authenticated(request.user) and request.user.pk or None

            res_status = 200
            result = {}

            try:
                form = CreateUserRatingForm(data=data, obj=self.get_object())
                if form.is_valid():
                    rating = form.save()
                    if rating:
                        result = rating.to_dict()

                        user_rating = form.cleaned_data.get('score')
                        if hasattr(rating, '_user_rating_deleted'):
                            user_rating = None

                        if user_rating:
                            user_rating = int(user_rating)

                        result['user_rating'] = user_rating
                else:
                    result = {'errors': form.errors}
                    res_status = 400
            except ValidationError as err:
                result = {'errors': err.message}
                res_status = 400

            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse(data=result, status=res_status)
            else:
                return HttpResponseRedirect(return_url)

        if not app_settings.STAR_RATINGS_ANONYMOUS:
            return login_required(_post)(request, *args, **kwargs)

        return _post(request, *args, **kwargs)

Home_app/templates/modules/footer_module.html
{% load static %}
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Por que fiz esse projeto ?</h5>
            <p class="mb-4">Queria e coloquei em pratica meus conhecimentos em programação e desenvolvimento web para criar um simulador de OLX</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i><label for=""></label> jhone.test14@gmail.com</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="{% url 'Home_app:Home' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="{% url 'Home_app:Shop' %}"><i class="fa fa-angle-right mr-2"></i>Compre</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Minha Conta</h5>
                    <div class="d-flex flex-column justify-content-start">
                        {% if user.is_authenticated %}
                            <a class="text-secondary mb-2" href="{% url 'Perfil_app:Perfil' %}"><i class="fa fa-angle-right mr-2"></i>Perfil</a>
                            <a class="text-secondary mb-2" href="/accounts/logout/"><i class="fa fa-angle-right mr-2"></i>Sair</a>
                            <a class="text-secondary mb-2" href="{% url 'Home_app:vender_produto' %}"><i class="fa fa-angle-right mr-2"></i>Vender Produto</a>
                            <a class="text-secondary mb-2" href="{% url 'Home_app:historico_publicacao' %}"><i class="fa fa-angle-right mr-2"></i>Ver Historico</a>
                            <a class="text-secondary mb-2" href="{% url 'Home_app:historicos' %}"><i class="fa fa-angle-right mr-2"></i>Ver Historico de Compras</a>
                        {% else %}
                            <a class="text-secondary mb-2" href="/accounts/login/"><i class="fa fa-angle-right mr-2"></i>Login</a>
                            <a class="text-secondary mb-2" href="/accounts/signup/"><i class="fa fa-angle-right mr-2"></i>Registrar</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="col-md-6 px-xl-0">
            <p class="mb-md-0 text-center text-md-left text-secondary">
                &copy; <a class="text-primary" href="#">Domain</a>. All Rights Reserved. Designed
                by
                <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
            </p>
        </div>
        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
        </div>
    </div>
</div>

Home_app/templates/modules/navbar_module.html
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
        <div class="col-lg-3 d-none d-lg-block">
            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; padding: 0 30px;">
                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categorias</h6>
                <i class="fa fa-angle-down text-dark"></i>
            </a>
            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">
                <div class="navbar-nav w-100">
                    {% comment %} <div class="nav-item dropdown dropright">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Dresses <i class="fa fa-angle-right float-right mt-1"></i></a>
                        <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">
                            <a href="" class="dropdown-item">Men's Dresses</a>
                            <a href="" class="dropdown-item">Women's Dresses</a>
                            <a href="" class="dropdown-item">Baby's Dresses</a>
                        </div>
                    </div> {% endcomment %}
                    {% for categoria in categorias %}
                    <a href="" class="nav-item nav-link">{{categoria}}</a>
                    {% endfor %}
                    {% comment %} <a href="" class="nav-item nav-link">Shirts</a>
                    <a href="" class="nav-item nav-link">Jeans</a>
                    <a href="" class="nav-item nav-link">Swimwear</a>
                    <a href="" class="nav-item nav-link">Sleepwear</a>
                    <a href="" class="nav-item nav-link">Sportswear</a>
                    <a href="" class="nav-item nav-link">Jumpsuits</a>
                    <a href="" class="nav-item nav-link">Blazers</a>
                    <a href="" class="nav-item nav-link">Jackets</a>
                    <a href="" class="nav-item nav-link">Shoes</a> {% endcomment %}
                </div>
            </nav>
        </div>
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="{% url 'Home_app:Home' %}" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Desapeguei</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'Home_app:Home' %}" class="nav-item nav-link {% comment %} active {% endcomment %}">Home</a>
                        <a href="{% url 'Home_app:Shop' %}"  class="nav-item nav-link">Shop</a>
                        <div class="nav-item dropdown">
                            {% comment %} <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down mt-1"></i></a>
                            <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                <a href="{% url 'Home_app:Cart' %}" class="dropdown-item">Shopping Cart</a>
                                <a href="{% url 'Home_app:Checkout' %}" class="dropdown-item">Checkout</a>
                            </div> {% endcomment %}
                        </div>
                        {% comment %} Pagina de Contato {% endcomment %}
                        {% comment %} <a href="{% url 'Home_app:Contact' %}" class="nav-item nav-link">Contact</a> {% endcomment %}
                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        {% comment %} Sessão de carrinho {% endcomment %}
                        {% comment %} <a href="" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a>
                        <a href="" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">0</span>
                        </a> {% endcomment %}
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

Home_app/templates/modules/star_ratings.html
{% extends "star_ratings/widget_base.html" %}

Home_app/templates/modules/topbar_module.html
<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <a class="text-body mr-3" href="">.</a>
                <a class="text-body mr-3" href="">.</a>
                <a class="text-body mr-3" href="">.</a>
                <a class="text-body mr-3" href="">.</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-warning dropdown-toggle" data-toggle="dropdown">Minha Conta</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% if not user.is_authenticated %}
                            <button class="dropdown-item" type="button" onclick="location.href='/accounts/login/'">Login</button>
                            <button class="dropdown-item" type="button" onclick="location.href='/accounts/signup/'" >Registrar</button>
                            {% else %}
                            <button class="dropdown-item" type="button" onclick="location.href='{% url 'Perfil_app:Perfil' %}'">Perfil</button>
                            <button class="dropdown-item" type="button" onclick="location.href='/accounts/logout/'" >Sair</button>
                        {% endif %}
                    </div>
                </div>
                {% comment %} <div class="btn-group mx-2">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">USD</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">EUR</button>
                        <button class="dropdown-item" type="button">GBP</button>
                        <button class="dropdown-item" type="button">CAD</button>
                    </div>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">EN</button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <button class="dropdown-item" type="button">FR</button>
                        <button class="dropdown-item" type="button">AR</button>
                        <button class="dropdown-item" type="button">RU</button>
                    </div>
                </div> {% endcomment %}
            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-heart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                </a>
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-shopping-cart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">0</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="{% url 'Home_app:Home' %}" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Desapeguei</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form action="">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for products">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-primary">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Projeto no github:</p>
            <a href="https://github.com/Rip4568/Desapeguei/tree/master" targe="_blank">aqui</a>
        </div>
    </div>
</div>